name: Equipment Finance Corporation
description: Equipment Finance Corporation
#paginate: 10
# Build settings
markdown: kramdown
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.efc-finance.com" # the base hostname & protocol for your site
