#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e
set -o errexit
set -o errtrace

cd $(dirname $0)/..

DEBIAN_FRONTEND=noninteractive
MARKER_FILE="/usr/local/etc/vagrant_provision_marker"

# Only provision once
if [ -f "${MARKER_FILE}" ]; then
  exit 0
fi

rm -rf /var/lib/apt/lists/*
apt-get update -qq -y
apt-get install -qq -y build-essential bsdtar wget curl git
apt-get install -qq -y libgmp-dev zlib1g-dev libxml2-dev libxslt-dev python-dev

apt-add-repository ppa:brightbox/ruby-ng
apt-get update -qq -y
apt-get install ruby2.3 ruby2.3-dev -qq -y

ruby --version
gem install rubygems-update --no-ri --no-rdoc

#update_rubygems
gem update --system

gem install bundler --no-ri --no-rdoc

bundle install

bundle update

# Touch the marker file so we don't do this again
touch ${MARKER_FILE}
