#!/bin/bash

# script/deploy: Overwrites gh-pages branch with the latest build

set -e
set -o errexit
set -o errtrace

cd $(dirname $0)/..

source script/settings
GITHUB_REPONAME=$GITHUB_REPONAME \
GITHUB_PUBLISH_BRANCH=$GITHUB_PUBLISH_BRANCH \
rake site:publish
