#!/bin/bash

# script/new: Creates a new jekyll site

set -e
set -o errexit
set -o errtrace

cd $(dirname $0)/..

gem install bundler --no-ri --no-rdoc

bundle install

bundle update

bundle exec jekyll new . --force
