#!/bin/bash

# script/vagrant: Setup vagrant environment after cloning

set -e
set -o errexit
set -o errtrace

cd $(dirname $0)/..

ln -s /vagrant $HOME/website

source /vagrant/script/settings

/vagrant/script/bootstrap

#configure work folder
if [ ! -d $HOME_DIR ]
then
    ln -s /vagrant $HOME_DIR
    cd $HOME_DIR
fi

echo "cd ${HOME_DIR}" | sudo tee -a /home/vagrant/.bash_profile
echo "echo "gem: --no-ri --no-rdoc" > /home/vagrant/.gemrc"

#configure git
git config --global push.default simple
git config --global core.autocrlf input

#update editor configs
cp /vagrant/.inputrc /home/vagrant
cp /vagrant/.vimrc /home/vagrant

chown -R vagrant:vagrant /home/vagrant
